import { Theme } from "theme.slint";
import { IconButton, SvgIcon, PrimaryButton } from "elements.slint";
import { ListView } from "std-widgets.slint";


export global WindowBridge {
    in-out property <bool> sidebar-visible: true;
    in-out property <length> sidebar-width: 200px;

    callback drag-window();

    callback minimize-window();
    callback maximize-window();
    callback close-window();
}

component TitleBar inherits Rectangle {

    height: 40px;
    background: Theme.colors.third-col;
    TouchArea {
        moved => {
            WindowBridge.drag-window();
        }
        pointer-event(event) => {}
    }

    HorizontalLayout {
        Rectangle {
            width: 42px;
            height: 42px;

            IconButton {
                x: (parent.width - self.width) / 2;
                y: (parent.height - self.height) / 2;

                width: 28px;
                height: 28px;

                SvgIcon {
                    source: @image-url("icons/sidebar.svg");
                    fg: Theme.colors.third-font;
                    size: 18px;
                }

                clicked => { WindowBridge.sidebar-visible = !WindowBridge.sidebar-visible; }
            }
        }

        Rectangle {
            width: WindowBridge.sidebar-visible ? WindowBridge.sidebar-width : 0;
            animate width {
                duration: 75ms;
                easing: ease;
            }
        }

        Rectangle { }

        HorizontalLayout {
            IconButton {
                width: 40px;
                height: 40px;
                round: false;
                transform: false;
                SvgIcon {
                    source: @image-url("icons/minimize.svg");
                    fg: parent.hovered ? Theme.colors.primary-font : Theme.colors.third-font;
                    size: 18px;
                }

                clicked => {
                    debug("minimize-window");
                    WindowBridge.minimize-window();
                }
            }

            IconButton {
                width: 40px;
                height: 40px;
                round: false;
                transform: false;
                SvgIcon {
                    source: @image-url("icons/maximize.svg");
                    fg: parent.hovered ? Theme.colors.primary-font : Theme.colors.third-font;
                    size: 18px;
                }

                clicked => {
                    WindowBridge.maximize-window();
                }
            }

            IconButton {
                width: 40px;
                height: 40px;
                round: false;
                transform: false;
                SvgIcon {
                    source: @image-url("icons/close.svg");
                    fg: parent.hovered ? Theme.colors.primary-font : Theme.colors.third-font;
                    size: 18px;
                }

                clicked => {
                    WindowBridge.close-window();
                }
            }
        }
    }
}


component MainBody inherits VerticalLayout {

    height: 100%;
    width: 100%;

    TitleBar { }
	// MainBody
    HorizontalLayout {
        vertical-stretch: 1;
        Rectangle {
            width: 40px;
            background: WindowBridge.sidebar-visible ? Theme.colors.secondary-col : Theme.colors.primary-col;

            animate background {
                duration: 75ms;
                easing: ease;
            }

            VerticalLayout {
                padding-top: 8px;
                padding-bottom: 8px;
                cross-axis-alignment: center;

                Rectangle {
                    height: 8px;
                }

                IconButton {
                    width: 28px;
                    height: 28px;
                    SvgIcon {
                        source: @image-url("icons/tranfsers.svg");
                        fg: parent.hovered ? Theme.colors.primary-font : Theme.colors.third-font;
                        size: 18px;
                    }

                    clicked => {
                        debug("Opening transfers");
                    }
                }

                Rectangle {
                    vertical-stretch: 1;
                }

                IconButton {
                    width: 28px;
                    height: 28px;
                    SvgIcon {
                        source: @image-url("icons/settings.svg");
                        fg: parent.hovered ? Theme.colors.primary-font : Theme.colors.third-font;
                        size: 18px;
                    }

                    clicked => {
                        debug("Open settings.");
                    }
                }
            }
        }

        Rectangle {
            width: 1px;
            background: Theme.colors.third-col;
        }

        // Sidebar
        Rectangle {
            width: WindowBridge.sidebar-visible ? WindowBridge.sidebar-width : 0px;
            clip: true;
            background: Theme.colors.secondary-col;
            border-width: 1px;
            border-color: Theme.colors.secondary-col;

            animate width {
                duration: 75ms;
                easing: ease;
            }
        }
    }
}

component DevicesList { }

component Settings { }


component GeneralModal inherits Rectangle {

    in-out property <bool> open;
    callback on-close();
    callback on-enter();

    forward-focus: focus-scope;

    focus-scope := FocusScope {
        enabled: open;
        visible: open;

        changed enabled => {
            if (open) {
                self.focus();
            }
        }

        key-pressed(event) => {
            if (event.text == Key.Escape) {
                open = false;
                on-close();
                return accept;
            }
            if (event.text == "w"
                && (event.modifiers.control || event.modifiers.meta)) {
                open = false;
                on-close();
                return accept;
            }
            if (event.text == Key.Return) {
                on-enter();
                return accept;
            }
            return reject;
        }

        Rectangle {
            width: 100%;
            height: 100%;
            background: #00000077;
        }

        TouchArea {
            width: 100%;
            height: 100%;
            enabled: open;
            clicked => {
                open = false;
                on-close();
            }
        }

        @children
    }
}

component FoundNearbyModal { }

component OutcomingTransferOfferModal { }


component FileRow inherits Rectangle {
    in property <string> name: "";
    height: 36px;
    background: touch-area.has-hover ? Theme.colors.third-col : transparent;
    touch-area := TouchArea { }

    HorizontalLayout {
        Text {
            text: name;
        }
    }
}

export global IncomingTransferOfferBridge {
    in-out property <bool> open;
    in-out property <[string]> files;

    callback reject();
    callback accept();
}

export component IncomingTransferOfferModal inherits Rectangle {
    GeneralModal {
        open <=> IncomingTransferOfferBridge.open;

        Rectangle {
            width: min(512px, parent.width - 40px);
            height: min(256px,parent.height - 40px);
            clip: true;

            drop-shadow-color: #00000099;
            drop-shadow-blur: 28px;
            background: Theme.colors.primary-col;
            border-radius: 12px;
            border-width: 1px;
            border-color: Theme.colors.border-col;

            TouchArea {
                width: 100%;
                height: 100%;
                clicked => {}
            }

            VerticalLayout {
                padding: 20px;
                HorizontalLayout {
                    VerticalLayout {
                        alignment: center;
                        Text {
                            text: "New transfer offer";
                            font-family: Theme.font-heading;
                            font-size: 20px;
                            font-weight: 600;
                            color: Theme.colors.primary-font;
                        }
                    }
                }

                Rectangle {
                    height: 8px;
                }

                ListView {

                    vertical-scrollbar-policy: as-needed;
                    for file in IncomingTransferOfferBridge.files: FileRow {
                        name: file;
                    }
                }

                HorizontalLayout {
                    alignment: end;
                    PrimaryButton {
                        text: "Reject";
                        clicked => {
                        }
                    }

                    Rectangle {
                        width: 12px;
                    }

                    PrimaryButton {
                        text: "Accept";
                        clicked => {
                        }
                    }
                }
            }
        }
    }
}

    export component NectanWindow inherits Window {
    no-frame: true;
    background: transparent;
    title: "Nectan";
    preferred-width: 1128px;
    preferred-height: 720px;
    min-width: 400px;
    min-height: 200px;
    max-width: 20050px;
    max-height: 20050px;
    default-font-family: Theme.font-body;
    resize-border-width: 8px;

    Rectangle {
        width: 100%;
        height: 100%;
        background: Theme.colors.primary-col;
        border-width: 1px;
        border-color: #dddddd1b;
        border-radius: 8px;
        clip: true;
        MainBody { }

        IncomingTransferOfferModal { }
    }
}
