import { Theme } from "theme.slint";
import {
    IconButton,
    SvgIcon,
    PrimaryButton,
    GeneralModal,
} from "elements.slint";
import { ListView, VerticalBox } from "std-widgets.slint";
import { SettingsBridge, SettingsModal, SettingsRow } from "settings.slint";
import { TransfersBridge, Transfers, TransferItem } from "transfers.slint";
import {
    AddRemoteDeviceModal,
    AddDeviceBridge,
    ConnectionOfferBridge,
    ConnectionOfferModal,
} from "add_remote_modal.slint";
import { ErrorModal } from "error_modal.slint";
import {
    DeviceItem,
    DevicesBridge,
    DeviceStatus,
    DeviceScreen,
} from "devices.slint";
import { TreeNode, TreeList } from "path_tree.slint";
import {
    IncomingTransferOfferModal,
    IncomingTransferOfferBridge,
    OutcomingTransferModal,
    OutcomingTransferModalBridge,
} from "transfer_offer_modal.slint";
import { SearchBridge, Search, SearchBar } from "search.slint";

export {
    DeviceItem,
    AddDeviceBridge,
    TransferItem,
    DevicesBridge,
    TransfersBridge,
    ConnectionOfferBridge,
    IncomingTransferOfferBridge,
    OutcomingTransferModalBridge,
}
export enum Window { transfers, device, add_remote }

export global WindowBridge {

    callback reorder-requested(int, int);
    callback close-requested(int);

    in-out property <bool> nectan-modal-visible: false;

    in-out property <bool> sidebar-visible: true;
    in-out property <bool> sidebar-hover: true;
    in-out property <length> sidebar-width: 200px;

    in-out property <Window> current-window: transfers;
    in-out property <int> current-ref-id: 0;

    in-out property <length> border-radius: 12px;

    callback drag-window();

    callback minimize-window();
    callback maximize-window();
    callback close-window();
}


component ActionButton inherits Rectangle {
    height: 42px;
    in property <length> icon-size: 16px;
    in property <image> icon;
    in property <string> text;
    in property <color> icon-color: Theme.colors.fourth-col;
    in property <color> text-color: Theme.colors.third-font;

    callback clicked();

    transform-scale: touch.pressed ? 0.97 : 1.0;
    animate transform-scale { duration: 100ms; }

    border-radius: 12px;
    background: Theme.colors.third-col;

    states [
        hovered when touch.has-hover: {
            background: Theme.colors.fourth-col;
            tip.opacity: 1;
            in {
                animate tip.opacity {
                    delay: 500ms;
                    duration: 80ms;
                }
            }
            out {
                animate tip.opacity { duration: 80ms; }
            }
        }
    ]

    touch := TouchArea {
        clicked => {
            root.clicked();
        }
    }

    if icon != @image-url(""): SvgIcon {
        source: icon;
        fg: Theme.colors.third-font;
        size: icon-size;
    }

    tip := Rectangle {
        z: 4;
        x: root.width + 4px;
        height: 24px;
        width: self.min-width + 20px;
        border-radius: 4px;
        background: Theme.colors.primary-col;
        border-color: Theme.colors.fourth-col;
        border-width: 1px;
        opacity: 0;
        Text {
            text: text;
            font-size: 12px;
            font-family: Theme.font-heading;
        }
    }
}


// export component MyTray inherits SystemTrayIcon {
//     icon: @image-url("icons/icon512.png");
//     tooltip: "Nectan";
//
//     callback show-window();
//     callback hide-window();
//
//     Menu {
//         MenuItem {
//             title: "Show";
//             activated => { show-window(); }
//         }
//
//         MenuItem {
//             title: "Hide";
//             activated => { hide-window(); }
//         }
//     }
// }

component NectanModal inherits GeneralModal {

    open <=> WindowBridge.nectan-modal-visible;

    Rectangle {
        width: min(620px, parent.width * 0.8);
        height: min(420px, parent.height * 0.8);

        background: Theme.colors.primary-col;
        border-radius: 14px;
        border-width: 1px;
        border-color: Theme.colors.third-col;
        clip: true;

        VerticalLayout {
            alignment: start;
            padding-top: 64px;
            cross-axis-alignment: center;

            Image {
                source: @image-url("icons/tray.png");
                width: 96px;
                height: 96px;
            }

            Rectangle {
                height: 8px;
            }

            Text {
                text: "Nectan";
                font-family: "Montserrat";
                color: Theme.colors.primary-font;
                font-size: 42px;
                font-weight: 700;
            }

            Text {
                text: "1.0.0";
                font-family: Theme.font-body;
                font-size: 13px;
                font-weight: 500;
                color: Theme.colors.third-font;
            }

            Rectangle {
                height: 96px;
            }

            SettingsRow {
                width: 420px;
                title: "Source code";
                subtitle: "Leave a star if you find Nectan useful.";

                PrimaryButton {
                    text: "Open";
                    image: @image-url("icons/github.svg");
                    clicked => {
                        SettingsBridge.username-modal = true;
                    }
                }
            }
        }
    }
}

component SidebarDevice inherits Rectangle {

    in property <DeviceItem> device;
    in property <bool> selected: false;

    height: 36px;
    border-radius: 12px;

    background: drag.dragging ? Theme.colors.fourth-font : selected ? Theme.colors.fourth-col : area.has-hover ? Theme.colors.third-col : transparent;

    transform-scale: area.pressed ? 0.99 : 1.0;
    animate transform-scale { duration: 100ms; }

    callback clicked;
    drag := DragArea {
        data: Api.make-data();
        allow-move: true;
        allow-copy: true;
        drag-image: @image-url("icons/link.svg");

        HorizontalLayout {
            padding-left: 12px;
            alignment: start;
            cross-axis-alignment: center;

            Rectangle {
                height: 6px;
                width: 6px;
                border-radius: 4px;
                background: device.status == DeviceStatus.online ? #ff9800 :
                    (device.status == DeviceStatus.nearby ? #0288d1 : Theme.colors.third-font);
            }

            Rectangle {
                width: 4px;
            }

            Text {
                vertical-alignment: center;
                text: device.name;
                color: Theme.colors.primary-font;
                font-size: 13px;
                font-weight: 600;
                font-family: Theme.font-heading;
            }
        }

        area := TouchArea {
            width: 100%;
            height: 100%;
            clicked => { root.clicked(); }
        }
    }
}

export global Api {
    pure callback make-data() -> data-transfer;
    pure callback can-drop() -> DragAction;
    callback dropped();
}

export component NectanWindow inherits Window {

    title: "Nectan";
    preferred-width: 1128px;
    preferred-height: 720px;
    min-width: 400px;
    min-height: 200px;
    default-font-family: Theme.font-body;
    resize-border-width: 8px;

    no-frame: true;
    background: transparent;

    in-out property <bool> error_open: false;
    in-out property <string> error_title: "";
    in-out property <string> error_message: "";
    callback show-error(string, string);
    callback close-error();

    show-error(title, message) => {
        root.error_open = true;
        root.error_message = message;
        root.error_title = title;
    }

    forward-focus: focus-scope;

    focus-scope := FocusScope {
        focus-on-click: true;
        width: 100%;
        height: 100%;

        init => {
            self.focus();
        }

        key-pressed(event) => {

            if (event.text == Key.S
                && (event.modifiers.control || event.modifiers.meta)) {
                WindowBridge.sidebar-visible = !WindowBridge.sidebar-visible;
                WindowBridge.sidebar-hover = false;
                return accept;
            }
            return reject;
        }

        TouchArea {
            width: 100%;
            height: 100%;
            scroll-event(event) => {
                if event.delta-x > 10px {
                    WindowBridge.sidebar-visible = true;
                }
                if event.delta-x < -10px {
                    WindowBridge.sidebar-visible = false;
                }
                return accept;
            }
        }

        Rectangle {
            width: 100%;
            height: 100%;
            background: Theme.colors.primary-col;
            border-width: 1px;
            border-color: Theme.colors.fourth-col;
            border-radius: 12px;
            padding: 20px;
            clip: true;

            Rectangle {
                x: 0;
                z: 1;
                width: WindowBridge.sidebar-visible ? 0 : WindowBridge.sidebar-hover ? WindowBridge.sidebar-width + 60px : 20px;
                sidebar-toggle := TouchArea {
                    pointer-event(event) => {
                        if self.mouse-x > WindowBridge.sidebar-width {
                            WindowBridge.sidebar-hover = false;
                        }
                        if self.mouse-x < 20px {
                            WindowBridge.sidebar-hover = true;
                        }
                    }
                }
            }

            Rectangle {
                x: WindowBridge.sidebar-visible ? 0 : (WindowBridge.sidebar-hover ? 4px : -WindowBridge.sidebar-width);
                width: WindowBridge.sidebar-width;
                z: 2;
                background: Theme.colors.primary-col;
                height: parent.height - 8px;
                border-radius: 8px;
                border-width: 1px;
                border-color: WindowBridge.sidebar-visible ? transparent : Theme.colors.border-col;

                animate x, border-color {
                    duration: 128ms;
                    easing: ease;
                }

                VerticalLayout {
                    padding: 8px;
                    padding-bottom: 0px;

                    HorizontalLayout {
                        alignment: space-between;
                        padding-left: 4px;

                        IconButton {
                            width: 28px;
                            height: 28px;

                            Image {
                                source: @image-url("icons/tray.png");
                                width: 16px;
                                height: 16px;
                            }

                            clicked => {
                                WindowBridge.nectan-modal-visible = true;
                            }
                        }

                        IconButton {
                            width: 28px;
                            height: 28px;
                            SvgIcon {
                                source: @image-url("icons/sidebar.svg");
                                fg: parent.hovered ? Theme.colors.secondary-font : Theme.colors.fourth-font;
                                size: 16px;
                            }

                            clicked => {
                                WindowBridge.sidebar-visible = !WindowBridge.sidebar-visible;
                            }
                        }
                    }

                    Rectangle {
                        height: 8px;
                    }

                    SearchBar { }

                    Rectangle {
                        height: 8px;
                    }

                    GridLayout {
                        spacing: 8px;
                        Row {

                            ActionButton {
                                z: 3;
                                horizontal-stretch: 1;
                                icon: @image-url("icons/link.svg");
                                text: "Add new device";
                                clicked => {
                                    AddDeviceBridge.add_device_open = true;
                                }
                            }

                            ActionButton {
                                z: 2;
                                horizontal-stretch: 1;
                                icon: @image-url("icons/tranfsers.svg");
                                icon-size: 17px;
                                text: "Open transfers";
                                clicked => {
                                    WindowBridge.current-window = Window.transfers;
                                }
                            }

                            ActionButton {
                                z: 1;
                                horizontal-stretch: 1;
                                icon: @image-url("icons/search.svg");
                                text: "Search";
                                clicked => {
                                    WindowBridge.current-window = Window.transfers;
                                }
                            }
                        }
                    }

                    Rectangle {
                        height: 8px;
                    }

                    for d[i] in DevicesBridge.devices: SidebarDevice {
                        device: d;
                        selected: true;
                        clicked => {
                            DevicesBridge.device-details-open-idx = i;
                            WindowBridge.current-window = Window.device;
                        }
                    }

                    Rectangle { }

                    HorizontalLayout {
                        alignment: space-between;
                        IconButton {
                            width: 28px;
                            height: 28px;
                            SvgIcon {
                                source: @image-url("icons/settings.svg");
                                fg: parent.hovered ? Theme.colors.secondary-font : Theme.colors.fourth-font;
                                size: 16px;
                            }

                            clicked => {
                                SettingsBridge.settings-open = true;
                            }
                        }

                        IconButton {
                            width: 28px;
                            height: 28px;
                            SvgIcon {
                                source: @image-url("icons/plus.svg");
                                fg: parent.hovered ? Theme.colors.secondary-font : Theme.colors.fourth-font;
                                size: 16px;
                            }

                            clicked => {
                                AddDeviceBridge.add_device_open = true;
                            }
                        }
                    }

                    Rectangle {
                        height: 4px;
                    }
                }
            }

            HorizontalLayout {
                spacing: 8px;
                padding: 8px;
                padding-left: !WindowBridge.sidebar-visible ? 8px : WindowBridge.sidebar-width;

                animate x, padding-left {
                    duration: 128ms;
                    easing: ease;
                }

                Rectangle {
                    background: Theme.colors.secondary-col;
                    border-radius: 8px;

                    if WindowBridge.current-window == Window.device: DeviceScreen { }

                    if WindowBridge.current-window == Window.transfers: Transfers { }
                }
            }
        }

        if SettingsBridge.settings_open: SettingsModal { }

        if WindowBridge.nectan-modal-visible: NectanModal { }

        if AddDeviceBridge.add_device_open:  AddRemoteDeviceModal { }

        if SearchBridge.visible: Search { }

        if OutcomingTransferModalBridge.sending-open: OutcomingTransferModal { }
    }
}
