import { Theme } from "theme.slint";

export component SvgIcon inherits Image {
    in property <color> fg: Theme.colors.primary-font;
    in property <length> size: 20px;
    colorize: root.fg;
    width: root.size;
    height: root.size;
}

export component IconButton inherits Rectangle {
    in property <string> text;
    in property <color> fg: Theme.colors.third-font;
    in property <bool> round: true;
    in property <bool> transform: true;
    in property <color> inner-bg: red;
    out property <bool> hovered: area.has-hover;
    out property <bool> pressed: area.pressed;
    callback clicked <=> area.clicked;

    inner := Rectangle {
        width: root.width;
        height: root.height;
        border-radius: root.round ? 4px : 0px;
        background: root.inner-bg != red ? root.inner-bg : (area.pressed ? Theme.colors.hover-col : (area.has-hover ? Theme.colors.hover-col : transparent));

        animate width, height, y {
            duration: 80ms;
            easing: ease-out;
        }

        states [
            pressed when area.pressed: {
                width: root.transform ? root.width * 0.983 : root.width;
                height: root.transform ? root.height * 0.983 : root.height;
                y: 1.5px;
            }
        ]

        content := Rectangle {

            @children

            animate width, height {
                duration: 80ms;
                easing: ease-out;
            }
        }
    }

    area := TouchArea {
        mouse-cursor: pointer;
    }
}

export component PrimaryButton {
    in property <string> text;
    in property <bool> alt: false;
    callback clicked;
    in property <image> image;

    height: 30px;
    width: max(81px, layout.preferred-width);

    animate width {
        duration: 200ms;
        easing: ease-out;
    }

    Rectangle {
        height: 100%;
        width: 100%;
        border-radius: 6px;
        background: Theme.colors.primary-font;
        border-width: root.alt ? 1px : 0px;
        border-color: Theme.colors.hover-col;

        animate background {
            duration: 100ms;
            easing: ease-out;
        }
        layout := HorizontalLayout {
            padding-left: 12px;
            padding-right: 12px;
            alignment: image.height > 0 ? start : center;

            if root.image.height > 0:  VerticalLayout {
                alignment: center;
                Image {
                    source: root.image;
                    colorize: root.alt ? Theme.colors.third-font : Theme.colors.third-col;
                    width: 16px;
                    height: 16px;
                }
            }
            if root.image.height > 0: Rectangle {
                width: 8px;
            }

            Text {
                text: root.text;
                font-size: 12px;
                font-weight: 600;
                vertical-alignment: center;
                color: Theme.colors.primary-col;
            }
        }

        touch := TouchArea {
            width: 100%;
            height: 100%;
            mouse-cursor: pointer;
            clicked => {
                root.clicked();
            }
        }
    }
}
