import { ScrollView, TextEdit, VerticalBox, LineEdit } from "std-widgets.slint";
import { Theme } from "theme.slint";
import { PrimaryButton, GeneralModal, PlainLineEdit } from "elements.slint";

export struct ShortcutItem {
    title: string,
    keys: [string],
    show_border: bool,
}

export struct ShortcutGroup {
    category: string,
    items: [ShortcutItem],
}

export component KeyBadge {
    in property <string> key-name;

    Rectangle {
        height: 26px;
        min-width: 36px;
        border-radius: 5px;
        background: Theme.colors.third-font;

        Rectangle {
            y: -1.25px;
            width: 100%;
            height: 24px;
            border-radius: 5px;
            background: Theme.colors.primary-font;

            Text {
                text: root.key-name;
                color: Theme.colors.primary-col;
                font-family: "Rubik";

                font-size: 11px;
                font-weight: 600;
                horizontal-alignment: center;
                vertical-alignment: center;
            }
        }
    }
}

component ShortcutKeys {
    in property <[string]> keys;

    HorizontalLayout {
        spacing: 8px;
        alignment: center;

        for key[idx] in root.keys: HorizontalLayout {
            spacing: 8px;

            if idx > 0: Text {
                text: "+";
                color: Theme.colors.primary-font;
                font-size: 12px;
                font-weight: 600;
                width: 8px;
                horizontal-alignment: center;
                vertical-alignment: center;
            }

            KeyBadge {
                key-name: key;
            }
        }
    }
}

export component SettingsRow {
    in property <string> title;
    in property <string> subtitle;

    HorizontalLayout {
        alignment: space-between;

        VerticalLayout {
            spacing: 2px;
            alignment: start;

            Text {
                text: root.title;
                color: Theme.colors.primary-font;
                font-size: 13px;
                font-weight: 600;
            }

            Text {
                text: root.subtitle;
                color: Theme.colors.third-font;
                font-size: 12px;
            }
        }

        VerticalLayout {
            alignment: center;
            @children
        }
    }
}


component ShortcutGroupView {
    in property <string> category;
    in property <[ShortcutItem]> items;

    Rectangle {
        border-radius: 8px;
        border-width: 1px;
        border-color: Theme.colors.border-col;

        VerticalLayout {
            padding: 16px;
            spacing: 0px;

            Text {
                text: root.category;
                color: Theme.colors.third-font;
                font-size: 11px;
                font-weight: 600;
            }

            Rectangle {
                height: 10px;
            }

            for item in root.items: Rectangle {
                height: 42px;

                VerticalLayout {
                    HorizontalLayout {
                        alignment: space-between;

                        Text {
                            text: item.title;
                            color: Theme.colors.primary-font;
                            font-size: 13px;
                            font-weight: 600;
                            vertical-alignment: center;
                        }

                        ShortcutKeys {
                            keys: item.keys;
                        }
                    }

                    if item.show_border: Rectangle {
                        height: 1px;
                        border-color: Theme.colors.border-col;
                    }
                }
            }
        }
    }
}


component SettingsTab inherits Rectangle {
    in-out property <int> active-tab;
    in property <string> tab;
    in property <int> tab-id;

    height: 28px;
    border-radius: 6px;
    background: active-tab == tab-id
        ? Theme.colors.secondary-col
        : (general.has-hover ? Theme.colors.secondary-col : transparent);

    Text {
        x: 12px;
        y: (parent.height - self.height) / 2;
        text: tab;
        color: active-tab == tab-id
            ? Theme.colors.primary-font
            : (general.has-hover ? Theme.colors.primary-font : Theme.colors.third-font);
        font-size: 13px;
        font-weight: 500;
    }

    general := TouchArea {
        enabled: SettingsBridge.settings_open;
        clicked => {
            active-tab = tab-id;
        }
    }
}

component BlockedTab inherits Rectangle {

    width: 100%;
    height: 100%;
    opacity: SettingsBridge.active-tab == 3 ? 1.0 : 0.0;

    VerticalLayout {
        padding: 20px;
        spacing: 12px;
        alignment: start;

        Text {
            text: "Blocked devices";
            color: Theme.colors.primary-font;
            font-size: 20px;
            font-weight: 700;
        }

        Rectangle {
            height: 4px;
        }
    }
}

component SettingsGeneralTab inherits Rectangle {

    width: 100%;
    height: 100%;
    opacity: SettingsBridge.active-tab == 0 ? 1.0 : 0.0;

    VerticalLayout {
        padding: 20px;
        spacing: 12px;
        alignment: start;

        Text {
            text: "General settings";
            color: Theme.colors.primary-font;
            font-size: 20px;
            font-weight: 700;
        }

        Rectangle {
            height: 4px;
        }

        SettingsRow {
            title: "Nazwa użytkownika";
            subtitle: SettingsBridge.username;

            PrimaryButton {
                text: "Zmień";

                clicked => {
                    SettingsBridge.username-modal = true;
                }
            }
        }

        Rectangle {
            height: 1px;
            background: Theme.colors.border-col;
        }

        SettingsRow {
            title: "Społeczność";
            subtitle: "Dołącz do serwera Discord Nectan";

            PrimaryButton {
                text: "Dołącz";

                clicked => {
                    SettingsBridge.join_discord();
                }
            }
        }

        Rectangle {
            height: 1px;
            background: Theme.colors.border-col;
        }

        SettingsRow {
            title: "GitHub";
            subtitle: "Nectan is open source. If you like the software, leave a star.";

            PrimaryButton {
                text: "Open";

                clicked => {
                    SettingsBridge.open_github();
                }
            }
        }

        Rectangle {
            height: 1px;
            background: Theme.colors.border-col;
        }

        SettingsRow {
            title: "Polityka prywatności";
            subtitle: "Zobacz naszą politykę prywatności";

            PrimaryButton {
                text: "Otwórz";

                clicked => {
                    SettingsBridge.open_privacy();
                }
            }
        }

        Rectangle {
            height: 1px;
            background: Theme.colors.border-col;
        }

        SettingsRow {
            title: "Theme";
            subtitle: "Change theme of application";
            PrimaryButton {
                text: Theme.mode == "dark" ? "Dark" : "Light";
                clicked => {
                    Theme.toggle-mode();
                }
            }
        }

        Rectangle {
            height: 1px;
            background: Theme.colors.border-col;
        }

        SettingsRow {
            title: "Zresetuj Nectan";
            subtitle: "Przywraca aplikację do stanu początkowego.";

            PrimaryButton {
                text: "Resetuj";

                clicked => {
                }
            }
        }
    }
}

component SettingShortcutsTab inherits Rectangle {

    private property <[ShortcutGroup]> shortcut-groups: [
        {
            category: "NAVIGATION",
            items: [
                { title: "Go to search", keys: ["Ctrl", "K"], show_border: true },
                { title: "Open next tab", keys: ["Ctrl", "Tab"], show_border: true },
                { title: "Open previous tab", keys: ["Ctrl", "Shift", "Tab"], show_border: true },
                { title: "Go back", keys: ["Alt", "←"], show_border: true },
                { title: "Go forward", keys: ["Alt", "→"], show_border: false }
            ]
        },
        {
            category: "EDITING",
            items: [
                { title: "Undo", keys: ["Ctrl", "Z"], show_border: true },
                { title: "Redo", keys: ["Ctrl", "Shift", "Z"], show_border: true },
                { title: "Duplicate line", keys: ["Ctrl", "D"], show_border: true },
                { title: "Delete line", keys: ["Ctrl", "Shift", "K"], show_border: true },
                { title: "Comment line", keys: ["Ctrl", "/"], show_border: false }
            ]
        }
    ];

    width: 100%;
    height: 100%;
    opacity: SettingsBridge.active-tab == 1 ? 1.0 : 0.0;

    ScrollView {
        width: 100%;
        height: 100%;
        enabled: SettingsBridge.settings_open;

        VerticalLayout {
            padding: 20px;
            spacing: 20px;

            Text {
                text: "Keyboard shortcuts";
                color: Theme.colors.primary-font;
                font-size: 20px;
                font-weight: 700;
            }

            for group in shortcut-groups: ShortcutGroupView {
                category: group.category;
                items: group.items;
            }
        }
    }
}

export component SettingsModal inherits GeneralModal {
    open <=> SettingsBridge.settings_open;

    Rectangle {
        width: min(820px, parent.width - 40px);
        height: min(560px,parent.height - 40px);
        clip: true;

        drop-shadow-color: #00000099;
        drop-shadow-blur: 28px;
        background: Theme.colors.primary-col;
        border-radius: 12px;
        border-width: 1px;
        border-color: Theme.colors.border-col;

        TouchArea {
            width: 100%;
            height: 100%;
            clicked => {}
        }

        HorizontalLayout {

            Rectangle {
                width: 156px;

                VerticalLayout {
                    padding: 8px;
                    spacing: 4px;

                    SettingsTab {
                        active-tab <=> SettingsBridge.active-tab;
                        tab-id: 0;
                        tab: "Ogólne";
                    }

                    SettingsTab {
                        active-tab <=> SettingsBridge.active-tab;
                        tab-id: 1;
                        tab: "Shortcuts";
                    }

                    SettingsTab {
                        active-tab <=> SettingsBridge.active-tab;
                        tab-id: 2;
                        tab: "Advanced";
                    }

                    SettingsTab {
                        active-tab <=> SettingsBridge.active-tab;
                        tab-id: 3;
                        tab: "Blocked";
                    }
                }
            }

            Rectangle {
                width: 1px;
                background: Theme.colors.border-col;
            }

            Rectangle {
                SettingsGeneralTab { }

                SettingShortcutsTab { }

                BlockedTab { }
            }
        }
    }
}

export global SettingsBridge {

    in-out property <bool> username-modal: false;
    in-out property <bool> settings_open: false;
    in-out property <int> active-tab: 0;

    in-out property <string> username: "Siema";
    in-out property <bool> autostart;
    in-out property <bool> local-mode;

    callback join_discord();
    callback open_github();
    callback open_privacy();
    callback toggle_autostart();
    callback change-username(string);
}


export component ChangeUsernameModal inherits Rectangle {
    property <string> new-username;
    GeneralModal {
        open <=> SettingsBridge.username-modal;

        on-close => {}
        on-enter => {
            SettingsBridge.change-username("LUJ");
        }

        Rectangle {

            width: min(520px, parent.width - 80px);
            height: min(256px, parent.height - 80px);

            animate width, height {
                duration: 200ms;
                easing: cubic-bezier(0.34, 1, 0.64, 1);
            }

            drop-shadow-color: #00000099;
            drop-shadow-blur: 28px;
            background: Theme.colors.primary-col;
            border-radius: 12px;
            border-width: 1px;
            border-color: Theme.colors.border-col;
            clip: true;

            TouchArea {
                width: 100%;
                height: 100%;
                clicked => {}
            }

            VerticalLayout {
                padding: 20px;

                VerticalLayout {
                    spacing: 12px;

                    HorizontalLayout {
                        VerticalLayout {
                            alignment: start;
                            Text {
                                text: "Change username";
                                font-size: 20px;
                                color: Theme.colors.primary-font;
                                font-family: Theme.font-heading;
                                font-weight: 600;
                            }

                            HorizontalLayout {
                                alignment: start;

                                Text {
                                    text: "Change your username visible to other devices.";
                                    font-size: 13px;
                                    color: Theme.colors.secondary-font;
                                }
                            }
                        }
                    }

                    Rectangle { }

                    Rectangle {
                        border-radius: 8px;
                        background: Theme.colors.secondary-col;
                        VerticalLayout {
                            PlainLineEdit {
                                placeholder-text: "Enter username";
                                input-text <=> new-username;
                            }
                        }
                    }

                    Rectangle { }

                    HorizontalLayout {
                        alignment: end;
                        PrimaryButton {
                            text: "Cancel";
                            alt: true;
                            clicked => {
                                SettingsBridge.username-modal = false;
                            }
                        }

                        Rectangle {
                            width: 12px;
                        }

                        PrimaryButton {
                            text: "Save";
                            clicked => {
                                SettingsBridge.change-username("asd");
                            }
                        }
                    }
                }
            }
        }
    }
}
