import { ScrollView, TextEdit, VerticalBox, LineEdit } from "std-widgets.slint";
import { Theme } from "theme.slint";
import { PrimaryButton, PlainLineEdit, GeneralModal } from "elements.slint";

export component SettingsRow {
    in property <string> title;
    in property <string> subtitle;

    HorizontalLayout {
        alignment: space-between;

        VerticalLayout {
            spacing: 2px;
            alignment: start;

            Text {
                text: root.title;
                color: Theme.colors.primary-font;
                font-size: 13px;
                font-weight: 600;
            }

            Text {
                text: root.subtitle;
                color: Theme.colors.third-font;
                font-size: 12px;
            }
        }

        VerticalLayout {
            alignment: center;
            @children
        }
    }
}


component SettingsTab inherits Rectangle {
    in-out property <int> active-tab;
    in property <string> tab;
    in property <int> tab-id;

    height: 28px;
    border-radius: 6px;
    background: active-tab == tab-id
        ? Theme.colors.secondary-col
        : (general.has-hover ? Theme.colors.secondary-col : transparent);

    Text {
        x: 12px;
        y: (parent.height - self.height) / 2;
        text: tab;
        color: active-tab == tab-id
            ? Theme.colors.primary-font
            : (general.has-hover ? Theme.colors.primary-font : Theme.colors.third-font);
        font-size: 13px;
        font-weight: 500;
    }

    general := TouchArea {
        enabled: SettingsBridge.settings_open;
        clicked => {
            active-tab = tab-id;
        }
    }
}

component BlockedTab inherits Rectangle {

    width: 100%;
    height: 100%;
    opacity: SettingsBridge.active-tab == 3 ? 1.0 : 0.0;

    VerticalLayout {
        padding: 20px;
        spacing: 12px;
        alignment: start;

        Text {
            text: "Blocked devices";
            color: Theme.colors.primary-font;
            font-size: 20px;
            font-weight: 700;
        }

        Rectangle {
            height: 4px;
        }
    }
}

component SettingsGeneralTab inherits Rectangle {

    width: 100%;
    height: 100%;
    opacity: SettingsBridge.active-tab == 0 ? 1.0 : 0.0;

    VerticalLayout {
        padding: 20px;
        spacing: 12px;
        alignment: start;

        Text {
            text: "General settings";
            color: Theme.colors.primary-font;
            font-size: 20px;
            font-weight: 700;
        }

        Rectangle {
            height: 4px;
        }

        SettingsRow {
            title: "Username";
            subtitle: SettingsBridge.username;

            PrimaryButton {
                text: "Change";

                clicked => {
                    SettingsBridge.username-modal = true;
                }
            }
        }

        Rectangle {
            height: 1px;
            background: Theme.colors.border-col;
        }

        SettingsRow {
            title: "Community";
            subtitle: "Join Nectan discord server";

            PrimaryButton {
                text: "Join";

                clicked => {
                    SettingsBridge.join_discord();
                }
            }
        }

        Rectangle {
            height: 1px;
            background: Theme.colors.border-col;
        }

        SettingsRow {
            title: "GitHub";
            subtitle: "Nectan is open source. If you like the software, leave a star.";

            PrimaryButton {
                text: "Open";

                clicked => {
                    SettingsBridge.open_github();
                }
            }
        }

        Rectangle {
            height: 1px;
            background: Theme.colors.border-col;
        }

        SettingsRow {
            title: "Privary policy";
            subtitle: "Read our privacy policy";

            PrimaryButton {
                text: "Read";

                clicked => {
                    SettingsBridge.open_privacy();
                }
            }
        }

        Rectangle {
            height: 1px;
            background: Theme.colors.border-col;
        }

        SettingsRow {
            title: "Theme";
            subtitle: "Change theme of application";
            PrimaryButton {
                text: Theme.mode == "dark" ? "Dark" : "Light";
                clicked => {
                    Theme.toggle-mode();
                }
            }
        }

        Rectangle {
            height: 1px;
            background: Theme.colors.border-col;
        }

        SettingsRow {
            title: "Reset Nectan";
            subtitle: "Bring Nectan to its initial state";

            PrimaryButton {
                text: "Reset";

                clicked => {
                }
            }
        }
    }
}

component SettingShortcutsTab inherits Rectangle {

    width: 100%;
    height: 100%;
    opacity: SettingsBridge.active-tab == 1 ? 1.0 : 0.0;

    ScrollView {
        width: 100%;
        height: 100%;
        enabled: SettingsBridge.settings_open;

        VerticalLayout {
            padding: 20px;
            spacing: 20px;

            Text {
                text: "Keyboard shortcuts";
                color: Theme.colors.primary-font;
                font-size: 20px;
                font-weight: 700;
            }
        }
    }
}

export component SettingsModal inherits Rectangle {

    GeneralModal {
        open <=> SettingsBridge.settings_open;

        Rectangle {
            width: min(820px, parent.width - 40px);
            height: min(560px,parent.height - 40px);
            clip: true;

            drop-shadow-color: #00000099;
            drop-shadow-blur: 28px;
            background: Theme.colors.primary-col;
            border-radius: 12px;
            border-width: 1px;
            border-color: Theme.colors.border-col;

            TouchArea {
                width: 100%;
                height: 100%;
                clicked => {}
            }

            HorizontalLayout {

                Rectangle {
                    width: 156px;

                    VerticalLayout {
                        padding: 8px;
                        spacing: 4px;

                        SettingsTab {
                            active-tab <=> SettingsBridge.active-tab;
                            tab-id: 0;
                            tab: "General";
                        }

                        SettingsTab {
                            active-tab <=> SettingsBridge.active-tab;
                            tab-id: 1;
                            tab: "Shortcuts";
                        }

                        SettingsTab {
                            active-tab <=> SettingsBridge.active-tab;
                            tab-id: 2;
                            tab: "Advanced";
                        }

                        SettingsTab {
                            active-tab <=> SettingsBridge.active-tab;
                            tab-id: 3;
                            tab: "Blocked";
                        }
                    }
                }

                Rectangle {
                    width: 1px;
                    background: Theme.colors.border-col;
                }

                Rectangle {
                    SettingsGeneralTab { }

                    SettingShortcutsTab { }

                    BlockedTab { }
                }
            }
        }
    }
}

export global SettingsBridge {

    in-out property <bool> username-modal: false;
    in-out property <bool> settings-open: false;
    in-out property <int> active-tab: 0;

    in-out property <string> username: "Siema";
    in-out property <bool> autostart;
    in-out property <bool> local-mode;

    callback join_discord();
    callback open_github();
    callback open_privacy();
    callback toggle_autostart();
    callback change-username(string);
}


export component ChangeUsernameModal inherits Rectangle {
    property <string> new-username;
    GeneralModal {
        open <=> SettingsBridge.username-modal;

        on-close => {}
        on-enter => {
            SettingsBridge.change-username("LUJ");
        }

        Rectangle {

            width: min(520px, parent.width - 80px);
            height: min(256px, parent.height - 80px);

            animate width, height {
                duration: 200ms;
                easing: cubic-bezier(0.34, 1, 0.64, 1);
            }

            drop-shadow-color: #00000099;
            drop-shadow-blur: 28px;
            background: Theme.colors.primary-col;
            border-radius: 12px;
            border-width: 1px;
            border-color: Theme.colors.border-col;
            clip: true;

            TouchArea {
                width: 100%;
                height: 100%;
                clicked => {}
            }

            VerticalLayout {
                padding: 20px;

                VerticalLayout {
                    spacing: 12px;

                    HorizontalLayout {
                        VerticalLayout {
                            alignment: start;
                            Text {
                                text: "Change username";
                                font-size: 20px;
                                color: Theme.colors.primary-font;
                                font-family: Theme.font-heading;
                                font-weight: 600;
                            }

                            HorizontalLayout {
                                alignment: start;

                                Text {
                                    text: "Change your username visible to other devices.";
                                    font-size: 13px;
                                    color: Theme.colors.secondary-font;
                                }
                            }
                        }
                    }

                    Rectangle { }

                    Rectangle {
                        border-radius: 8px;
                        background: Theme.colors.secondary-col;
                        VerticalLayout {

                            PlainLineEdit {
                                placeholder-text: "Enter username";
                                input-text <=> new-username;
                            }
                        }
                    }

                    Rectangle { }

                    HorizontalLayout {
                        alignment: end;
                        PrimaryButton {
                            text: "Cancel";
                            alt: true;
                            clicked => {
                                SettingsBridge.username-modal = false;
                            }
                        }

                        Rectangle {
                            width: 12px;
                        }

                        PrimaryButton {
                            text: "Save";
                            clicked => {
                                SettingsBridge.change-username("asd");
                            }
                        }
                    }
                }
            }
        }
    }
}
