// import { Theme } from "theme.slint";
// import { IconButton, SvgIcon, Spinner, PrimaryButton } from "elements.slint";
// import { Transfers } from "transfers.slint";
// import { SettingsBridge } from "settings.slint";
// import { DeviceRow, DeviceScreen, DevicesBridge } from "devices.slint";
// import { AddDeviceBridge } from "add_remote_modal.slint";
//
//
// component SplitTab inherits Rectangle {
//     vertical-stretch: 1;
//     horizontal-stretch: 1;
//     border-radius: 8px;
//     background: hov.has-hover ? Theme.colors.fourth-col : Theme.colors.third-col;
//
//     animate background { duration: 40ms; }
//
//     hov := TouchArea { }
// }
//
// export component TabsGrid inherits GridLayout {
//     spacing: 8px;
//     padding: 8px;
//     padding-left: !WindowBridge.sidebar-visible ? 8px : WindowBridge.sidebar-width;
//     in-out property <int> tabs;
//
//     animate x, padding-left {
//         duration: 128ms;
//         easing: ease;
//     }
//
//     Row {
//
//         SplitTab {
//             background: black;
//             colspan: 2;
//         }
//     }
//
//     Row {
//         SplitTab { }
//
//         SplitTab { }
//     }
//
//     Row {
//         SplitTab { }
//     }
//
//     Row { }
//
//     Row { }
// }
